import { IVehicleTypeModel, IBrandModel, IBrandVersionModel, IFuelTypeModel, IFuelMeasurementModel, IInsuranceModel, IVehicleStatusModel,  IWorkLocationModel, IProjectModel, IProjectTypeModel, IGeneralData } from './demographics.interface';

export interface IVehicle {    
    vehicleID: string;
    vehicle_type?: string;
    vehicle_typeId: string;
    vehicle_code: string;
    name: string;
    yearofManufacturer: string;
    make?: string;
    model?: string;
    color: string;
    vehicleImage: string,
    vehicleGroup: string;
    regNo: string;
    engineNo: string;
    chassisNo: string;
    serialNo: string;
    warrantyPeriod: string;
    validity: string;
    fuelType?: string;
    fuelMeasurementIn?: string;
    trackUsage: string;
    currentUser: string;
    currentUserDL: string;
    ownership: string;
    insuranceValid: Date;
    insuranceNo: string;
    insuranceAmt: string;
    insuranceCopy: String,
    insuranceAgent?: string;
    roadTaxValid: Date,
    roadTaxNo: string;
    roadTaxAmt: string;
    roadTaxCopy: String;
    vehicleStatus?: string;
    assigned?: string;
    employeeID: string;
    organizationId: string;
    projectDetails?: string;
    projectTypeDetails?: string;
    workLocation?: string;
    projectTypeId: string;
    Date: Date;
    creatorId: Number;
    updatedDate: Date;
    updateId: Number;
    updatedStatus: Number;
    assignedProject: Number;
}

export interface IFormattedVehicle {
    vehicleID: string;
    vehicle_type: IVehicleTypeModel;
    vehicle_typeId: string;
    vehicle_code: string;
    name: string;
    yearofManufacturer: string;
    make: IBrandModel;
    model: IBrandVersionModel;
    color: string;
    vehicleImage: string,
    vehicleGroup: string;
    regNo: string;
    engineNo: string;
    chassisNo: string;
    serialNo: string;
    warrantyPeriod: string;
    validity: string;
    fuelType: IFuelTypeModel;
    fuelMeasurementIn: IFuelMeasurementModel;
    trackUsage: string;
    currentUser: string;
    currentUserDL: string;    
    ownership: string;
    insuranceValid: Date;
    insuranceNo: string;
    insuranceAmt: string;
    insuranceCopy: String,
    insuranceAgent: IInsuranceModel;
    roadTaxValid: Date,
    roadTaxNo: string;
    roadTaxAmt: string;
    roadTaxCopy: String;    
    vehicleStatus: IVehicleStatusModel;
    //assigned: IAssignVehicleModel;
    assigned: string;
    employeeID: string;
    organizationId: string;
    projectDetails: IProjectModel;
    projectTypeDetails: IProjectTypeModel;
    workLocation: IWorkLocationModel;
    projectTypeId: string;
    Date: Date;
    creatorId: Number;
    updatedDate: Date;
    updateId: Number;
    updatedStatus: Number;  
    assignedProject: Number;
}
